
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x11\x9de\xf2\xb8\xcd\x8e\x1f\xddZ\x18E\xe6\x91NS'
    
_lr_action_items = {'STRING':([0,1,2,3,],[2,3,-2,-1,]),'$end':([0,1,2,3,],[-3,0,-2,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'tags_def_expression':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tags_def_expression","S'",1,None,None,None),
  ('tags_def_expression -> tags_def_expression STRING','tags_def_expression',2,'p_tags_def_expression','/home/vlkv/projects/reggata.git/src/parsers/tags_def_parser.py',13),
  ('tags_def_expression -> STRING','tags_def_expression',1,'p_tags_def_expression_atom','/home/vlkv/projects/reggata.git/src/parsers/tags_def_parser.py',18),
  ('tags_def_expression -> <empty>','tags_def_expression',0,'p_tags_def_expression_empty','/home/vlkv/projects/reggata.git/src/parsers/tags_def_parser.py',22),
]
