# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Dec 25 00:33:56 2010
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(659, 447)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_query = QtGui.QLineEdit(self.frame)
        self.lineEdit_query.setObjectName(_fromUtf8("lineEdit_query"))
        self.horizontalLayout.addWidget(self.lineEdit_query)
        self.pushButton_query_exec = QtGui.QPushButton(self.frame)
        self.pushButton_query_exec.setObjectName(_fromUtf8("pushButton_query_exec"))
        self.horizontalLayout.addWidget(self.pushButton_query_exec)
        self.pushButton_query_reset = QtGui.QPushButton(self.frame)
        self.pushButton_query_reset.setObjectName(_fromUtf8("pushButton_query_reset"))
        self.horizontalLayout.addWidget(self.pushButton_query_reset)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableView_items = QtGui.QTableView(self.frame)
        self.tableView_items.setObjectName(_fromUtf8("tableView_items"))
        self.verticalLayout_2.addWidget(self.tableView_items)
        self.verticalLayout_3.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 659, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_repo = QtGui.QMenu(self.menubar)
        self.menu_repo.setObjectName(_fromUtf8("menu_repo"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menuItem = QtGui.QMenu(self.menubar)
        self.menuItem.setObjectName(_fromUtf8("menuItem"))
        self.menuFix_integrity_errors = QtGui.QMenu(self.menuItem)
        self.menuFix_integrity_errors.setObjectName(_fromUtf8("menuFix_integrity_errors"))
        self.menuFix_hash_mismatch_error = QtGui.QMenu(self.menuFix_integrity_errors)
        self.menuFix_hash_mismatch_error.setObjectName(_fromUtf8("menuFix_hash_mismatch_error"))
        self.menuFix_file_not_found_error = QtGui.QMenu(self.menuFix_integrity_errors)
        self.menuFix_file_not_found_error.setObjectName(_fromUtf8("menuFix_file_not_found_error"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_tag_cloud = QtGui.QDockWidget(MainWindow)
        self.dockWidget_tag_cloud.setFloating(False)
        self.dockWidget_tag_cloud.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget_tag_cloud.setObjectName(_fromUtf8("dockWidget_tag_cloud"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.dockWidget_tag_cloud.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_tag_cloud)
        self.action_repo_create = QtGui.QAction(MainWindow)
        self.action_repo_create.setObjectName(_fromUtf8("action_repo_create"))
        self.action_repo_open = QtGui.QAction(MainWindow)
        self.action_repo_open.setObjectName(_fromUtf8("action_repo_open"))
        self.action_repo_close = QtGui.QAction(MainWindow)
        self.action_repo_close.setObjectName(_fromUtf8("action_repo_close"))
        self.action_item_add = QtGui.QAction(MainWindow)
        self.action_item_add.setObjectName(_fromUtf8("action_item_add"))
        self.action_user_create = QtGui.QAction(MainWindow)
        self.action_user_create.setObjectName(_fromUtf8("action_user_create"))
        self.action_user_login = QtGui.QAction(MainWindow)
        self.action_user_login.setObjectName(_fromUtf8("action_user_login"))
        self.action_user_logout = QtGui.QAction(MainWindow)
        self.action_user_logout.setObjectName(_fromUtf8("action_user_logout"))
        self.action_item_edit = QtGui.QAction(MainWindow)
        self.action_item_edit.setObjectName(_fromUtf8("action_item_edit"))
        self.action_item_add_many = QtGui.QAction(MainWindow)
        self.action_item_add_many.setObjectName(_fromUtf8("action_item_add_many"))
        self.action_user_change_pass = QtGui.QAction(MainWindow)
        self.action_user_change_pass.setObjectName(_fromUtf8("action_user_change_pass"))
        self.action_tools_tag_cloud = QtGui.QAction(MainWindow)
        self.action_tools_tag_cloud.setCheckable(True)
        self.action_tools_tag_cloud.setChecked(True)
        self.action_tools_tag_cloud.setEnabled(True)
        self.action_tools_tag_cloud.setObjectName(_fromUtf8("action_tools_tag_cloud"))
        self.action_item_view = QtGui.QAction(MainWindow)
        self.action_item_view.setObjectName(_fromUtf8("action_item_view"))
        self.action_item_add_many_rec = QtGui.QAction(MainWindow)
        self.action_item_add_many_rec.setObjectName(_fromUtf8("action_item_add_many_rec"))
        self.action_item_delete = QtGui.QAction(MainWindow)
        self.action_item_delete.setObjectName(_fromUtf8("action_item_delete"))
        self.action_item_view_m3u = QtGui.QAction(MainWindow)
        self.action_item_view_m3u.setObjectName(_fromUtf8("action_item_view_m3u"))
        self.action_help_about = QtGui.QAction(MainWindow)
        self.action_help_about.setObjectName(_fromUtf8("action_help_about"))
        self.action_item_view_image_viewer = QtGui.QAction(MainWindow)
        self.action_item_view_image_viewer.setObjectName(_fromUtf8("action_item_view_image_viewer"))
        self.action_item_check_integrity = QtGui.QAction(MainWindow)
        self.action_item_check_integrity.setObjectName(_fromUtf8("action_item_check_integrity"))
        self.action_item_fix_history_rec_error = QtGui.QAction(MainWindow)
        self.action_item_fix_history_rec_error.setObjectName(_fromUtf8("action_item_fix_history_rec_error"))
        self.action_item_fix_hash_error = QtGui.QAction(MainWindow)
        self.action_item_fix_hash_error.setObjectName(_fromUtf8("action_item_fix_hash_error"))
        self.action_item_update_file_hash = QtGui.QAction(MainWindow)
        self.action_item_update_file_hash.setObjectName(_fromUtf8("action_item_update_file_hash"))
        self.action_fix_file_not_found_try_find = QtGui.QAction(MainWindow)
        self.action_fix_file_not_found_try_find.setObjectName(_fromUtf8("action_fix_file_not_found_try_find"))
        self.action_fix_file_not_found_delete = QtGui.QAction(MainWindow)
        self.action_fix_file_not_found_delete.setObjectName(_fromUtf8("action_fix_file_not_found_delete"))
        self.action_fix_file_not_found_try_find_else_delete = QtGui.QAction(MainWindow)
        self.action_fix_file_not_found_try_find_else_delete.setObjectName(_fromUtf8("action_fix_file_not_found_try_find_else_delete"))
        self.action_item_rebuild_thumbnail = QtGui.QAction(MainWindow)
        self.action_item_rebuild_thumbnail.setObjectName(_fromUtf8("action_item_rebuild_thumbnail"))
        self.menu_repo.addAction(self.action_repo_create)
        self.menu_repo.addAction(self.action_repo_open)
        self.menu_repo.addAction(self.action_repo_close)
        self.menu.addAction(self.action_user_create)
        self.menu.addAction(self.action_user_login)
        self.menu.addAction(self.action_user_logout)
        self.menu.addAction(self.action_user_change_pass)
        self.menuFix_hash_mismatch_error.addAction(self.action_item_fix_hash_error)
        self.menuFix_hash_mismatch_error.addAction(self.action_item_update_file_hash)
        self.menuFix_file_not_found_error.addAction(self.action_fix_file_not_found_try_find)
        self.menuFix_file_not_found_error.addAction(self.action_fix_file_not_found_delete)
        self.menuFix_integrity_errors.addAction(self.menuFix_hash_mismatch_error.menuAction())
        self.menuFix_integrity_errors.addAction(self.action_item_fix_history_rec_error)
        self.menuFix_integrity_errors.addAction(self.menuFix_file_not_found_error.menuAction())
        self.menuItem.addAction(self.action_item_add)
        self.menuItem.addAction(self.action_item_add_many)
        self.menuItem.addAction(self.action_item_add_many_rec)
        self.menuItem.addSeparator()
        self.menuItem.addAction(self.action_item_edit)
        self.menuItem.addAction(self.action_item_rebuild_thumbnail)
        self.menuItem.addSeparator()
        self.menuItem.addAction(self.action_item_delete)
        self.menuItem.addSeparator()
        self.menuItem.addAction(self.action_item_view)
        self.menuItem.addAction(self.action_item_view_image_viewer)
        self.menuItem.addAction(self.action_item_view_m3u)
        self.menuItem.addSeparator()
        self.menuItem.addAction(self.action_item_check_integrity)
        self.menuItem.addAction(self.menuFix_integrity_errors.menuAction())
        self.menuTools.addAction(self.action_tools_tag_cloud)
        self.menuHelp.addAction(self.action_help_about)
        self.menubar.addAction(self.menu_repo.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuItem.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Reggata", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Query:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_query_exec.setText(QtGui.QApplication.translate("MainWindow", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_query_reset.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_repo.setTitle(QtGui.QApplication.translate("MainWindow", "&Repository", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "&User", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItem.setTitle(QtGui.QApplication.translate("MainWindow", "&Item", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFix_integrity_errors.setTitle(QtGui.QApplication.translate("MainWindow", "Fix integrity errors", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFix_hash_mismatch_error.setTitle(QtGui.QApplication.translate("MainWindow", "Fix file changed error", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFix_file_not_found_error.setTitle(QtGui.QApplication.translate("MainWindow", "Fix file not found error", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "&Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_tag_cloud.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tag cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.action_repo_create.setText(QtGui.QApplication.translate("MainWindow", "&New", None, QtGui.QApplication.UnicodeUTF8))
        self.action_repo_open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_repo_close.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_add.setText(QtGui.QApplication.translate("MainWindow", "Add &one", None, QtGui.QApplication.UnicodeUTF8))
        self.action_user_create.setText(QtGui.QApplication.translate("MainWindow", "&Create", None, QtGui.QApplication.UnicodeUTF8))
        self.action_user_login.setText(QtGui.QApplication.translate("MainWindow", "&Login", None, QtGui.QApplication.UnicodeUTF8))
        self.action_user_logout.setText(QtGui.QApplication.translate("MainWindow", "Log&out", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_edit.setText(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_add_many.setText(QtGui.QApplication.translate("MainWindow", "Add &many", None, QtGui.QApplication.UnicodeUTF8))
        self.action_user_change_pass.setText(QtGui.QApplication.translate("MainWindow", "Change &password", None, QtGui.QApplication.UnicodeUTF8))
        self.action_tools_tag_cloud.setText(QtGui.QApplication.translate("MainWindow", "Tag &cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_view.setText(QtGui.QApplication.translate("MainWindow", "&View with external app", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_add_many_rec.setText(QtGui.QApplication.translate("MainWindow", "Add many &recursively", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_delete.setText(QtGui.QApplication.translate("MainWindow", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_view_m3u.setText(QtGui.QApplication.translate("MainWindow", "Create m3u playlist and open it", None, QtGui.QApplication.UnicodeUTF8))
        self.action_help_about.setText(QtGui.QApplication.translate("MainWindow", "About Reggata", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_view_image_viewer.setText(QtGui.QApplication.translate("MainWindow", "View images with built-in viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_check_integrity.setText(QtGui.QApplication.translate("MainWindow", "Check &integrity", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_fix_history_rec_error.setText(QtGui.QApplication.translate("MainWindow", "Fix history rec error", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_fix_hash_error.setText(QtGui.QApplication.translate("MainWindow", "Try find file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_update_file_hash.setText(QtGui.QApplication.translate("MainWindow", "Update hash", None, QtGui.QApplication.UnicodeUTF8))
        self.action_fix_file_not_found_try_find.setText(QtGui.QApplication.translate("MainWindow", "Try find file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_fix_file_not_found_delete.setText(QtGui.QApplication.translate("MainWindow", "Delete item\'s reference to file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_fix_file_not_found_try_find_else_delete.setText(QtGui.QApplication.translate("MainWindow", "Try find file else delete link", None, QtGui.QApplication.UnicodeUTF8))
        self.action_item_rebuild_thumbnail.setText(QtGui.QApplication.translate("MainWindow", "Rebuild &thumbnail", None, QtGui.QApplication.UnicodeUTF8))

