# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Oct 25 16:03:32 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 373)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_query = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_query.setObjectName("lineEdit_query")
        self.horizontalLayout.addWidget(self.lineEdit_query)
        self.pushButton_query_exec = QtGui.QPushButton(self.centralwidget)
        self.pushButton_query_exec.setObjectName("pushButton_query_exec")
        self.horizontalLayout.addWidget(self.pushButton_query_exec)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame_tag_cloud = QtGui.QFrame(self.centralwidget)
        self.frame_tag_cloud.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_tag_cloud.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_tag_cloud.setObjectName("frame_tag_cloud")
        self.verticalLayout.addWidget(self.frame_tag_cloud)
        self.tableView_items = QtGui.QTableView(self.centralwidget)
        self.tableView_items.setObjectName("tableView_items")
        self.verticalLayout.addWidget(self.tableView_items)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 471, 29))
        self.menubar.setObjectName("menubar")
        self.menu_repo = QtGui.QMenu(self.menubar)
        self.menu_repo.setObjectName("menu_repo")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_repo_create = QtGui.QAction(MainWindow)
        self.action_repo_create.setObjectName("action_repo_create")
        self.action_repo_open = QtGui.QAction(MainWindow)
        self.action_repo_open.setObjectName("action_repo_open")
        self.action_repo_close = QtGui.QAction(MainWindow)
        self.action_repo_close.setObjectName("action_repo_close")
        self.action_repo_add_item = QtGui.QAction(MainWindow)
        self.action_repo_add_item.setObjectName("action_repo_add_item")
        self.action_user_create = QtGui.QAction(MainWindow)
        self.action_user_create.setObjectName("action_user_create")
        self.action_user_login = QtGui.QAction(MainWindow)
        self.action_user_login.setObjectName("action_user_login")
        self.action_user_logout = QtGui.QAction(MainWindow)
        self.action_user_logout.setObjectName("action_user_logout")
        self.menu_repo.addAction(self.action_repo_create)
        self.menu_repo.addAction(self.action_repo_open)
        self.menu_repo.addAction(self.action_repo_close)
        self.menu_repo.addAction(self.action_repo_add_item)
        self.menu.addAction(self.action_user_create)
        self.menu.addAction(self.action_user_login)
        self.menu.addAction(self.action_user_logout)
        self.menubar.addAction(self.menu_repo.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Reggata", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Query:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_query_exec.setText(QtGui.QApplication.translate("MainWindow", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_repo.setTitle(QtGui.QApplication.translate("MainWindow", "Repository", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.action_repo_create.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.action_repo_open.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_repo_close.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_repo_add_item.setText(QtGui.QApplication.translate("MainWindow", "Add item", None, QtGui.QApplication.UnicodeUTF8))
        self.action_user_create.setText(QtGui.QApplication.translate("MainWindow", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.action_user_login.setText(QtGui.QApplication.translate("MainWindow", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.action_user_logout.setText(QtGui.QApplication.translate("MainWindow", "Logout", None, QtGui.QApplication.UnicodeUTF8))

